### ISSUE TITLE
Date "according to Exif data" is sometimes wrong

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#1971]
In https://commons.wikimedia.org/wiki/File:Taiwan_white_caterpillar2018.jpg
you will observe "Date	1 November 2018 (according to Exif data)".
But if you scroll down to Metadata, you will find that is not the case.
App version: noted already on the page.

Please use the actual exif data date, not the upload date.
Nowhere in the exif data does it contain the upload date.

**Comment by misaochan** [comment]
Hi @jidanni , thanks for reporting this. This is a known issue (see #1854 ) and should be fixed in v2.9. :)

**Comment by misaochan** [comment]
Hi @jidanni , we just released this bugfix with v2.9 in beta. Could you please let us know if the problem is solved for you?

**Comment by nicolas-raoul** [comment]
This is a big problem and it still exists in 2.9.0.196~52ab393:
https://commons.wikimedia.org/w/index.php?title=File:%E3%82%A2%E3%83%AB%E3%83%95%E3%82%A1%E5%85%83%E9%BA%BB%E5%B8%83.jpg&oldid=337653865
I shot that image on December 4 (as can be seen in the EXIF section) but the metadata wikitext created by our app wrongfully contains `date={{According to EXIF data|2019-02-04}}` which is the date at which I _uploaded_ the picture.

This could bring us bad publicity, I received this on my talk page:

> Please upload D5300 images from a desktop computer, not from your mobile phone
>
> Hello, you might have already noticed, but the files you had taken with a Nikon D5300 camera had incorrect date information in {{information}}. For examples, File:アルファ元麻布.jpg and File:菊池家住宅 entrance.jpg had been actually taken on 4 December 2018, but the files initially showed 4 February 2019 as the date taken. These are, I believe, fatal errors, and it requires a hefty workload to remedy them manually. The reason such errors occur is that the Commons Mobile Application you are using is not smart enough to determine the appropriate dates. By using a desktop computer and Upload Wizard on commons, failures as such can be easily avoided, as it automatically adds dates based on the Exif of the images. As a user who added Category:December 2018 in Tokyo to your files, I ask you to do so, or you have to correct the date information by yourself. Please be aware that when an image was taken is as important as what it depicts. Regards,

We are already taking information from EXIF, I believe it is rather easy to fix, so I add the beginner-friendly tag.

**Comment by maskaravivek** [comment]
I would like to pick this up as I believe my recent changes might have broken it. We will include it in 2.10.0.

**Comment by misaochan** [comment]
Luckily the recent changes should not be on any published version of the app, just the alphas. Will hold 2.10 for it.

(Glad to see the alpha version is proving very useful, too! :))

**Comment by nicolas-raoul** [comment]
Note: I am having this issue but I never use Google Photos.

**Comment by maskaravivek** [comment]
Sorry, I named the PR Incorrectly. It fixes the issue for all uploads. Will edit the title when I get to my laptop.

**Comment by nicolas-raoul** [comment]
I just uploaded a picture taken on January 28, and it displays January 29:
https://commons.m.wikimedia.org/wiki/File:Otafukuzaka%2C_Roppongi_5_chome.jpg

**Comment by maskaravivek** [comment]
The problem is that we do not extract the date/time from EXIF so the summary is misleading. 

<img width="1048" alt="screenshot 2019-02-13 at 11 09 34 am" src="https://user-images.githubusercontent.com/3069373/52689338-e0c6fc80-2f7f-11e9-9e2d-e7b2ead6ba72.png">

As Google Photos do not return EXIF information(i tried a few 3rd party EXIF viewer apps to cross-check this), we started using `ContentResolver` to extract date/time. Sadly, we started doing it for all images and not just Google Photo images. **For the above image EXIF had the date/time but as mentioned, we use `ContentResolver` for all images.** 

Most of the time this date would match the actual EXIF date so no one would complain but differences can be noticed for different time zones. This is because EXIF doesn't specify the timezone. http://www.exiv2.org/tags.html

References to code to understand the flow: 

Extracting date time: 
https://github.com/commons-app/apps-android-commons/blob/master/app/src/main/java/fr/free/nrw/commons/filepicker/UploadableFile.java#L70

Setting page contents: 
https://github.com/commons-app/apps-android-commons/blob/master/app/src/main/java/fr/free/nrw/commons/contributions/Contribution.java#L156

Sending page contents while uploading: 
https://github.com/commons-app/apps-android-commons/blob/52ab39381eccb1d55231338b8c8ce7d6e57c4d29/app/src/main/java/fr/free/nrw/commons/upload/UploadService.java#L248

IMO, what we have been doing is incorrect and we should use the words "according to EXIF" in the summary. 

Please suggest, how to go about it. 

- Do not show file creation date if EXIF doesn't contain it. 
- Try to extract EXIF date and fallback to `ContentResolver` if EXIF is not present
- Change the wording from "according to EXIF" to something relevant. 

cc @misaochan @ashishkumar468 Please correct me if my understanding of the flow is incorrect.

**Comment by ashishkumar468** [comment]
I am also aware of the issue of not getting upload dates from the EXIF when uploaded via google photos. IMO as @maskaravivek  suggested, we should try to extract EXIF date and fallback to ContentResolver if EXIF is not present and similarly update the the display text "according to EXIF", based on the source of extraction.

**Comment by misaochan** [comment]
Agreed with @ashishkumar468

**Comment by maskaravivek** [comment]
Okay, thanks for the feedback. Will make these changes. :)

**Comment by maskaravivek** [comment]
> we should try to extract EXIF date and fallback to ContentResolver if EXIF is not present and similarly update the the display text "according to EXIF", based on the source of extraction.

If we have a fallback based on which we modify the display text then we need to introduce a `timestampSource` parameter in `Contribution`. That would require a schema update.

**Comment by misaochan** [comment]
Hmm, I just re-read the issue, and it seems we have 2 problems:

1. The Google Photos EXIF issue. IME, EXIF has always been a problem with Google Photos, i.e. this is not a bug that was introduced by our recent changes. In that case, it is not crucial to have the fix in 2.10.1 (good to have, but we shouldn't hold up the release)
2. @nicolas-raoul 's issue. He says he has never used Google Photos, yet the date/time issue for him is persisting. This means that #2438 did not cover his use case. Is this correct?

I think (1) can wait, but (2) needs to be looked into. @nicolas-raoul could you give us details on the steps you use to upload? Are you using Android stock gallery? Images stored on SD card or phone memory?

**Comment by nicolas-raoul** [comment]
I am at work so I can not research in detail, but checking my last few uploads, it seems like the dates look OK? https://commons.wikimedia.org/w/index.php?title=Special:ListFiles/Syced&ilshowall=1 Maybe it depends on the time of day?

I am using a Nexus 5, which does not have an external SD card, and recently I am mostly uploading pictures from a directory called `/storage/emulated/0/nico/from-pc`, example: https://commons.wikimedia.org/wiki/File:Y.S._Park_building_in_%E8%8A%8B%E6%B4%97%E5%9D%82.jpg
A picture uploaded from `/storage/emulated/0/DCIM/OpenCamera`: https://commons.wikimedia.org/wiki/File:Pink_lights_and_bubble_machine_in_Roppongi_Hills_Arena.jpg

I always either use the app's built-in folder selection, or share from Android's stock gallery application (LineageOS 7.1.2). I don't remember what picture I sent with each methods, but I can upload a picture with each method and link to them from here later this evening if you want.

**Comment by maskaravivek** [comment]
If the date is extracted from a source other than EXIF I will use this template for displaying the date: 

```
{{date|2009|1|9}} → 9 January 2009
```
This will appear as: 

<img width="566" alt="screen shot 2019-02-18 at 9 04 35 pm" src="https://user-images.githubusercontent.com/3069373/52961386-d57d3200-33c0-11e9-8945-edfc153909f4.png">


If it comes from EXIF I will use continue using the existing template. 

```
{{According to EXIF data|2009-01-09}}
```

This will keep appearing in the same old way. 

<img width="520" alt="screen shot 2019-02-18 at 9 05 28 pm" src="https://user-images.githubusercontent.com/3069373/52961436-f180d380-33c0-11e9-8560-ef979e4828e8.png">

**Comment by misaochan** [comment]
@maskaravivek Sounds good.

**Comment by maskaravivek** [comment]
@nicolas-raoul It would be great if you can confirm if this is fixed for you. It should be available in the latest alpha. :)

**Comment by nicolas-raoul** [comment]
I just uploaded one picture and it looks OK: https://commons.wikimedia.org/wiki/File:Artists_workshop_closed_down,_in_Imoaraizaka_%E8%8A%8B%E6%B4%97%E5%9D%82.jpg
Thanks! :-)

**Comment by Aschroet** [comment]
Are you sure it is fixed? The SandBot just came across fixing a date of a file that i uploaded not long ago with the latest beta version (2.10.2~66e1539a1) : https://commons.wikimedia.org/w/index.php?title=File:Raspberry_Pi_3_Wikidata.jpg&action=history. Maybe there is also a problem with the timezone?

**Comment by nicolas-raoul** [comment]
@Aschroet Thanks for reporting!
The original issue of this report was for date that were wrong by several months, so I guess it might be different, but still a problem of course.

**Comment by madisoncfallin** [comment]
Is this still available? I'd like to work on it

**Comment by nicolas-raoul** [comment]
@madisoncfallin Thanks! Please first try to reproduce the issue by uploading a picture and let us know (including at what exact time/timezone you took a picture, uploaded the picture, what its EXIF contained, and what metadata appears on the image's page at https://commons.wikimedia.org)

**Comment by madisoncfallin** [comment]
@nicolas-raoul That will be difficult, I don't actually have an Android device easily available....Is there a way I could fake it in Android Studio?

**Comment by nicolas-raoul** [comment]
Yes, it is actually easier in Android Studio, all web requests show up in logcat :-)

**Comment by nicolas-raoul** [comment]
In Android Studio, just download any picture from https://drive.google.com/drive/folders/1T5wfM16qb78XCvnf1Zunww4neg8BXJj6?usp=sharing and use for upload in the app. Thanks! :-)

**Comment by madisoncfallin** [comment]
I believe that I've repro'd the issue: https://commons.wikimedia.beta.wmflabs.org/wiki/File:MCF_Test_Photo.jpg

The "Date" shown in the "Summary" box isn't a date at all.

**Comment by nicolas-raoul** [comment]
Ah, the beta server does not have this template.
Please compile the app again with the "prodDebug" flavor, thanks!

**Comment by madisoncfallin** [comment]
@nicolas-raoul I just uploaded a photo on the prodDebug flavor: https://commons.wikimedia.org/wiki/File:MCF_Test_Photo_1.jpg

Is this the intended behavior? I would assume that the date of the photo should be the date it was taken, not the date it was uploaded.

**Comment by nicolas-raoul** [comment]
Thanks! All of the dates on that page actually seem correct to me. Upload dates are really the date the picture was uploaded, while shooting dates are really the date the picture was shot.

The problem is shown by this past upload (which has been corrected since):
https://commons.wikimedia.org/w/index.php?title=File:Raspberry_Pi_3_Wikidata.jpg&oldid=352178950
I highlighted the correct date in green and the erroneous dates in red:
![Screen Shot 2020-10-23 at 19 01 11](https://user-images.githubusercontent.com/99590/96990837-996d7d80-1562-11eb-85a0-c62fe9f611ef.png)
I notice that the picture was taken shortly before midnight: Maybe the app is rounding to the next hour or something similar? Would you mind trying again with a picture taken shortly before midnight?

**Comment by misaochan** [comment]
Just checking if anyone is still able to reproduce this issue?

**Comment by nicolas-raoul** [comment]
@madisoncfallin Could you please try to reproduce using this file taken shortly before midnight? https://drive.google.com/file/d/1vfTRupGatxi0W3TlGl8mF4-5Hk5vt4Fb/view I don't think the EXIF embeds any timezone information.

**Comment by misaochan** [comment]
Just to clarify (as the discussion has been long), it is the date in the template that needs to change to follow the EXIF data, right?

**Comment by nicolas-raoul** [comment]
Using the latest commit of https://github.com/commons-app/apps-android-commons/tree/4.0-release branch, I just uploaded the files below, cropped or not, rotated or original. Some have a one day difference between EXIF and `{{According to Exif data|`, some not:

One day difference:
- https://commons.wikimedia.org/wiki/File:%E6%A8%AA%E6%B5%9CYMCA.jpg taken at `18:02, 12 July 2022`, we generated `{{According to Exif data|2022-07-13}}`. Original (not edited).
- https://commons.wikimedia.org/wiki/File:Shibuya_Bridge_on_weekend_5.jpg `15:05, 17 July 2022`. Original.
- https://commons.wikimedia.org/wiki/File:Shibuya_Bridge_on_weekend_4.jpg original
- https://commons.wikimedia.org/wiki/File:Shibuya_Bridge_on_weekend_3.jpg original
- https://commons.wikimedia.org/wiki/File:Shibuya_Bridge_on_weekend_2.jpg original
- https://commons.wikimedia.org/wiki/File:Shibuya_Bridge_on_weekend.jpg original

Correct:
- https://commons.wikimedia.org/wiki/File:Red_panda_at_Nogeyama_Zoo.jpg taken at `13:48, 12 July 2022`, we generated `{{According to Exif data|2022-07-12}}`. Original.
- https://commons.wikimedia.org/wiki/File:Construction_around_Shibuya_station_6.jpg rotated
- https://commons.wikimedia.org/wiki/File:Red_panda_at_Nogeyama_Zoo_(lossless_crop_with_JPEG_Cropper).jpg cropped

**Comment by misaochan** [comment]
Thanks @nicolas-raoul ! Hmm, in that case the hypothesis re: saving date must be wrong, then? I have no idea what else could be the issue, as I don't see any pattern. Did you upload all of them through the same method (Contributions > Gallery > Stock Android Gallery)?

**Comment by subbass1** [comment]
As i am (heavily) affected: I choose multiple files with a file commander and hand over via "share". But I doubt this is relevant here.

**Comment by subbass1** [comment]
@misaochan: why the hypoth. then must be wrong? On his files I see identical capture and saving dates in the EXIF. Besides that: only 1 day difference could be timezone related and then another thing.

**Comment by misaochan** [comment]
Hi @subbass1 , great to see you here! If I understand correctly, @nicolas-raoul 's reports indicate that some of his pictures had the correct date even though he edited the pictures. And some of his pictures have the wrong date even though they are originals and he did not edit them. Nicolas can you confirm my interpretation of your post?

Also, @subbass1 are all of your wrong dates just 1 day late similar to Nicolas's, or does it vary (some 1 day late, some 3 days late, etc)? If it varies, are they all late, or are some early?

**Comment by subbass1** [comment]
@misaochan: here it's conistently this way (no timezone prob!): in the EXIF we have 2 fields/dates: "Erfassungszeitpunkt" (capture date) and "Speicherzeitpunkt" (saving date).  if they are the same, no problem. if not (this happens when you edit days later) the app errorously uses the saving date. And afaics the files by nicolas do show identical dates, so there can't be a problem related to this matter. A local saving date has no meaning afaics, it depends on the last edits on the file.

**Comment by misaochan** [comment]
What change exactly did you perform on 13 July? Could you describe the process of making that change? I understand from your post on the Village Pump that it involves Google Photos, but I need to know the process so I can test it.

**Comment by subbass1** [comment]
Yes, I always edit online (cutting, center etc.), and then for convenience first save on the phone before uploading in mass mode from there (also could be days later, but that makes no harm). The edits are being saved correctly by google photos on the files. The app should just ignore these field and always use "Erfassungszeitpunkt" (capture date, you called it "date and time of data generation")

**Comment by misaochan** [comment]
Sweet, I have successfully reproduced the issue! https://commons.wikimedia.org/wiki/File:Australian_possum.jpg Thanks so much @subbass1 , we hope to fix this soon.

Summary

There are 2 separate issues.

Issue 1 - Date of data generation vs file change date

This is the issue that @subbass1 is experiencing. To reproduce, edit a photo in Google Photos on your phone, then save the edit. Then "Share" and select the Commons app. I can confirm that this happens in 4.0-release as well.

Solution: always use date and time of data generation in EXIF, not file change date and time.

Issue 2 - 1 day late

This is the issue that @nicolas-raoul is experiencing. To be determined: Why does it happen sometimes and not at other times? My hypothesis is that it depends on the cutoff time of the "day". 

TODO: @nicolas-raoul if it's not too much trouble can you test uploading at different times of the day and see if there is a pattern? You are from +9 UTC, right?

**Comment by nicolas-raoul** [comment]
> [nicolas]' reports indicate that some of his pictures had the correct date even though he edited the pictures. And some of his pictures have the wrong date even though they are originals and he did not edit them.

True

> You are from +9 UTC, right?

Yes

> If you upload before 3pm then no problems, if you upload after 3pm then it's 1 day late

Great finding, before/after 3pm seems to indeed be the key! I guess you meant: If the _picture's EXIF date_ (not sure which one, since the EXIF dates found in EXIF seem to always be identical for me) is before 3pm then no problem. If the picture's EXIF date is after 3pm then `According to Exif data` is set to 1 day too late. I will keep uploading more pictures to validate this hypothesis.

Should I create a new issue about Issue 2?

**Comment by whym** [comment]
I have created #5017. Is it the same thing as Issue 1 above? (Sorry, I didn't catch up with the recent comments here.) I used the beta cluster, which might complicated things needlessly.

**Comment by misaochan** [comment]
Hi @whym ! Yes, #5017 looks like a duplicate of Issue 1. We can close it and I will link to it in my summary comment above.

@nicolas-raoul Thanks! I think for now I will just link to #3635 in my summary comment, and later on that can serve as detailed discussion for Issue 2 if needed. I prefer not to move things around too much before @neslihanturan has the chance to catch up on this, as the discussion flow will be broken and that may be confusing. Once she has read this, she can choose to move Issue 2 to #3635 if she wants.

**Comment by whym** [comment]
Agreed with having the discussion in one place for now.

To support what @misaochan said above (hi, it's been a while!), among ``ExifInterface``'s four timestamp-related methods, `getDateTimeOriginal()` seems like the one we want, at least if the device behaves as expected.

- `getDateTime():` this is the one the app currently uses. It is confusingly the last modification timestamp and can be updated when the image is edited apparently. [Exiftool's documentation](https://exiftool.org/TagNames/EXIF.html) seems to support this understanding. (Find the row for "ModifyDate".) https://github.com/commons-app/apps-android-commons/blob/f8a8f9207028a6fb5a35483c040821f22daf755e/app/src/main/java/fr/free/nrw/commons/filepicker/UploadableFile.java#L127
- `getDateTimeOriginal():` this is the one we would want to use.
- `getDateTimeDigitized()`: this can perhaps be used instead when DateTimeOriginal is unavailable. (But probably in most cases, just using getDateTimeOriginal() is fine.)
- `getGpsDateTime():` same as above

Also, it seems like the timezone offsets embedded in EXIF can be obtained by `getAttribute()` of ExifInterface. This might help when working on the timezone issue discussed above.

**Comment by nicolas-raoul** [comment]
(about issue 2)

I have tested with around 100 pictures, I can confirm that being at UTC+9, any picture taken after 3pm leads to a `According to Exif data` which is +1 day compared to the picture's taken date documented in EXIF.

Apparently [EXIF timezones can't be trusted](https://photo.stackexchange.com/a/97149/1498), and actually when it comes to the `According to Exif data` template the app **must ignore timezones**. If a picture was taken at `2022 July 20 hh:mm:ss timezone TZ`, we should not even try to interpret `hh:mm:ss` nor `TZ`, instead we must just take the `2022 July 20` part and use it directly without performing any calculation.

`getDateTimeOriginal()` returns a long (Unix epoch time when the picture was taken, example: `1658168053000`) in the GMT timezone, so this method does not solve issue 2.
Instead, we must use `exif.getAttribute(ExifInterface.TAG_DATETIME)`. It returns a String (same example: `2022:07:18 18:14:13`), which we can substring to get the year, month, day parts to insert directly into the `According to Exif data` template.

**Comment by whym** [comment]
If we are to start from the string representation of the DateTimeOriginal value, I would expect lots of irregularities from different devices that Android supports. (I do think it's a great idea, though.) It might worth checkiing out [how MediaWiki parses that](https://github.com/wikimedia/mediawiki/blob/99aad54ea856479fa29fcced81734dd0c17ddcbd/includes/media/FormatMetadata.php#L343) in PHP.

**Comment by nicolas-raoul** [comment]
(about issue 2)

> I would expect lots of irregularities from different devices that Android supports, custom camera apps, and pictures the user might import from elsewhere

People have been transferring their pictures from their Android/etc devices for 17 years to upload via the web Upload Wizard, so I believe it is robust enough for us :-)

Thanks a lot for the PHP link! Judging from it, Mediawiki can parse the following EXIF DateTimeOriginal/etc formats:
```
/^(?:\d{4}):(?:\d\d):(?:\d\d) (?:\d\d):(?:\d\d):(?:\d\d)$/D
/^(?:\d{4}):(?:\d\d):(?:\d\d) (?:\d\d):(?:\d\d)$/D
/^(?:\d{4}):(?:\d\d):(?:\d\d)$/D
0000:00:00 00:00:00
    :  :     :  :  
```
In other words, we can implement this pseudo-code:

1. year = substring from 0 length 4, then parse integer.
2. month = substring from 5, length 2, then parse integer.
3. day = substring from 8 length 2, then parse integer.
4. If any of the above failed, skip and do not output the template (_because it means that the EXIF does not contain a usable date_).
5. Concatenate `{{According to Exif data|` + year + `-` + month + `-` + day + `}}` and output that.

**Comment by whym** [comment]
I wrote [a database query](https://quarry.wmcloud.org/query/66237) and found a few edge cases of DateTimeOriginal values.

* "03/03/2019 1:57" [Venice_8.jpg](https://commons.wikimedia.org/wiki/File:Venice_8.jpg)
* "2018-07-23 18:40:47" [Kirkevoll_skole_panorama.jpg](https://commons.wikimedia.org/wiki/File:Kirkevoll_skole_panorama.jpg)
* "2018-10-07 13:18:19" [Berganvannet,_Re.jpg](https://commons.wikimedia.org/wiki/File:Berganvannet,_Re.jpg) Berganvannet,_Re_2.jpg Berganvannet,_Re_3.jpg

These were uploaded with different versions of the app, and I don't fully understand what was going on precisely. (If I remember it correctly, in some cases, the app might have wrongly inserted the current date as EXIF dates.)

I think it wouldn't hurt to support the "2018-07-23" format. Exiftool's implementation seems to do that, with `/^(\d+)[-:](\d+)[-:](\d+)\s+(\d+):(\d+):(\d+)(.*)/`: https://github.com/exiftool/exiftool/blob/1e17485cbb372a502e5b9d052d01303db735e6fa/lib/Image/ExifTool.pm#L5881

Not sure about "03/03/2019".

**Comment by nicolas-raoul** [comment]
Thanks a lot for the research! Is `03/03/2019` format a rare exception, or is it quite prevalent? It could be a bug in an app's EXIF generator, by the way `Date and time of digitizing` in the EXIF of the same panoramic picture uses a more standard year-first format.

How about we just not generate the `According to Exif data` template if we do not recognize the date?

**Comment by misaochan** [comment]
> How about we just not generate the According to Exif data template if we do not recognize the date?

Sounds like a good option to me, if it's considered acceptable by the Commons community.

**Comment by whym** [comment]
Yes, I forgot mention but we can say from the same results that [nicolas-raoul's simple method](https://github.com/commons-app/apps-android-commons/issues/1971#issuecomment-1191495565) will work for 99+% of the cases (both of the ":" and "-" delimiters). It would be nice to handle the 1% or fewer irregular cases, but that can wait.

**Comment by whym** [comment]
In general, I think it's safe to assume the community expectation is "as good as UploadWizard or better".

> >  How about we just not generate the According to Exif data template if we do not recognize the date?
> Sounds like a good option to me, if it's considered acceptable by the Commons community?

I assume "not generate" means inserting the current date, which is what the app does.

For comparizon, when EXIF doesn't provide the date, UploadWizard asks for it. If I try to leave it empty, I cannot proceed. (It says "This field is required.") In this way, UW tries to find the correct date, with additional user interaction.

I think here (when EXIF doesn't provide the date) we can either

- add a similar step to ask the user to enter the date manually
- or use {{Upload date}} to make it clearer it's the current date

To do the latter, we will probably need another category in addition to TEMPLATE_DATE_ACC_TO_EXIF and TEMPLATE_DATA_OTHER_SOURCE:
https://github.com/commons-app/apps-android-commons/blob/7476b0a24d1dd14683ee2d775ad7d5a2b8968683/app/src/main/java/fr/free/nrw/commons/upload/PageContentsCreator.java#L20-L24

This could be done independently from fixing DateTime/DateTimeOriginal confusion. (It also could be done together.)

**Comment by misaochan** [comment]
Hmm, if it's not possible to proceed without a date via the Upload Wizard, then we should not do that indeed. 

> add a similar (mandatory) step to ask the user to enter the date manually

I would prefer not to do this as IMO this is the more complex option from a dev, UI and tester perspective

> or use {{Upload date}} to make it clearer it's the current date

I would be in favour of this if all are agreed. @nicolas-raoul @neslihanturan ?

**Comment by nicolas-raoul** [comment]
Using {{Upload date}} when EXIF date can't be determined sounds good to me 🙂

**Comment by whym** [comment]
I just realized that things would be a bit more complicated than I said in the last comment, because it looks like it's not the current timestamp but the last modified date on the local file system that's used when EXIF timestamp is unavailable. (I was testing with newly copied files, so I didn't notice the difference, sorry.)

https://github.com/commons-app/apps-android-commons/blob/f8a8f9207028a6fb5a35483c040821f22daf755e/app/src/main/java/fr/free/nrw/commons/filepicker/UploadableFile.java#L103

Using the current date (or the upload date) instead can make sense, but that would be a change that we might want to more carefully consider.

It seems like this topic ("how to better represent timestamps from different sources") might be better discussed elsewhere, anyway, though.

**Comment by misaochan** [comment]
Hmm, thanks for bringing that up @whym . As this only affects edge cases, I think I will go ahead and merge and release #5019 as the vast majority of cases can be handled by that, and time is of the essence. Could you create a new issue for this topic?

**Comment by misaochan** [comment]
Should tentatively be able to do the v4.0.2 release with this by tomorrow.

**Comment by misaochan** [comment]
@subbass1 I have released v4.0.2 with this bugfix, it should be available for beta testing on the Play Store in a few hours' time. Could you please register for beta testing, make sure the app is updated to v4.0.2 (you can check the version via "About") and test it with an edited photo? Thanks a lot!

**Comment by misaochan** [comment]
@subbass1 The v4.0.3 release has gone through, would appreciate help with testing it. :)

**Comment by subbass1** [comment]
Ok, will do (perhaps someone could look at my last uploads (but if I upload the same days the photos were taken one can't check it). But besides that: *please* look in the very annoying bug that the app stops working completely quite often. (I think you know my text facts.) Also stop/start uploading manually doesn't help. Than it's necessary to de- and reinstall completely. I'm really annoyed, can't work this way. Given the fact that this is a high end phone, working otherwise without any problems (One Plus 9) I can't see the problem. It also doesn't depend of the amount of files  uploaded simultaneously. I try to do not more than 10-15 at one step (but more would be better!). Also most of the time I restart before and don't use other apps simultaneously (besides the browser) - it doesn't help. I guess more than 60% of my uploads stop this way ..   greets Martin

Am 5. August 2022 11:34:39 MESZ schrieb Josephine Lim ***@***.***>:
***@***.*** The v4.0.3 release has gone through, would appreciate help with testing it. :)
>

**Comment by misaochan** [comment]
@subbass1 Sorry, I'm not familiar with that issue - I was under the impression that you were crashing on Settings, is that not fixed now?

For the issue of the ANR (app not responding), could you create a new issue using our issue tracker so that a volunteer can take it up please? Thanks!

**Comment by whym** [comment]
Just a data point to confirm the EXIF bug was fixed, [a file uploaded a few days ago](https://commons.wikimedia.org/wiki/File:Apollo_and_Marsyas_music_contest.jpg) has a correct timestamp. (The version used was 4.0.5~f03b7dd8d.)

The wiki text says

> |date={{According to Exif data|2022-08-27}}

EXIF says
> Date and time of data generation	2022-08-27T13:25:08
> File change date and time	2022-08-30T23:50:06

If not for the bug fix, the wiki text would have said 2022-08-30.
