### ISSUE TITLE
Fix all-capital strings in strings.xml

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#2935]
**Summary:** 

As mentioned at #2873 , we should avoid using all-capital strings in strings.xml file, since this can cause some problems during translation. There are some all-capital strings under strings.xml file, they should be fixed, and capitalized in the java code or layout xmls depending on where they are used.

Note: While implementing this PR, many files can be edited. So please make sure you didn't change any extra lines, ie. inserting additional spaces. 

Note2: Ideally can be implemented after #2931 is merged to prevent possible conflicts.

**Comment by henryhucsc** [comment]
Hi,
I would like to contribute to this one. But I am a beginner who has no experiences of contributing to open source project on Github. May I ask a few questions?
I followed your [instruction](https://github.com/commons-app/apps-android-commons/wiki/Quick-start-guide-for-Developers)
1. I searched file named strings.xml, there are many files. I am not sure why one should I work on? some of them are not English.
2. For this task, do I need to create a separate branch? or I just edit on the original files then commit changes and pull requests?
Thank you very much for answering my questions.

**Comment by neslihanturan** [comment]
Welcome to team @henryhucsc 
1- Just the default one should be edited, others will be updated after translations by translators.
2- Yes you should create a new branch, see: https://github.com/commons-app/apps-android-commons/wiki/Developer-workflow

**Comment by henryhucsc** [comment]
Thank you very much for answering my questions.
I just finished fixing all-capital strings in strings.xml and pulled request to master.

**Comment by harshchinu** [comment]
Hi,
I would like to contribute to this one. But I am a beginner who has no experiences of contributing to open source project on Github. May I ask a few questions?
I saw some issue and that already solved i am an complete beginner to opensource that why would you like to guide me

**Comment by sherlockbeard** [comment]
#2999 in this pull i made the necessary changes required in layout files and in the string value file

**Comment by charlygg** [comment]
Hi,
I would like to contribute, I was reviewing the PR referenced to this issue and I have one question, Do you need fix all-capital string in java code?

**Comment by neslihanturan** [comment]
Hi @charlygg , thanks for your interest. Actually this issue is not for all capital strings. Ie. "FAQ" is all capital and should be all capital. Additionally this issue is only for strings located in strings.xml file. On the other hand I believe this issue is solved by previous pull request of @sherlockbeard . I am not sure why github didn't close this automatically. Please don't hesitate to ask your further questions about contributing.

**Comment by neslihanturan** [comment]
This ##3015 solves the issue.. Github didn't close this issue because pull reques't didn't followed our pull request template and didn't include issue link. Anyway, this one is solved.

**Comment by sherlockbeard** [comment]
@neslihanturan #2999 was the pr for it . But i by mistake pushed some other change it . Then i closed that to start a fresh pr (about which i forgot due to my exams)  . So this issue still exists . I will send pr in 24 hours.

**Comment by neslihanturan** [comment]
Oh okay, sorry for the confusion. Please ping me when ready. I thought I merged your changes earlier though @sherlockbeard .
