### ISSUE TITLE
Uploading a new image shows the previous image uploaded on screen until the current image is uploaded completely

### ISSUE THREAD

**Issue by kamrutha** [commons-app/apps-android-commons#3267]
**Summary:** 

While uploading a new image the app shows the previous image until it is fully uploaded 

**Steps to reproduce:** 
What did you expect the app to do, and what did you see instead?
New image to be shown instead of the old one

**Device and Android version:** 

Redmi 6 Pro 
Andriod version 9PKQ1.180917.001
 

**Screen-shots:** 
**BEFORE UPLOADING**
![WhatsApp Image 2019-12-03 at 12 37 05 PM](https://user-images.githubusercontent.com/34261526/70029959-2ebff600-15ce-11ea-95f9-12e9cbc7ccd1.jpeg)
**WHILE UPLOADING**
![WhatsApp Image 2019-12-03 at 12 37 05 PM (1)](https://user-images.githubusercontent.com/34261526/70029964-32ec1380-15ce-11ea-83e4-c48c0d3f03c1.jpeg)
**AFTER UPLOADING**
![WhatsApp Image 2019-12-03 at 12 37 05 PM (2)](https://user-images.githubusercontent.com/34261526/70029967-34b5d700-15ce-11ea-9058-22a76dbc2cee.jpeg)
**Would you like to work on the issue?**
Yes

**Comment by nicolas-raoul** [comment]
Thanks for spotting this bug!
We only allow people to work on one bug at a time. Do you want to work on this one later, after solving the one you are currently assigned to? :-)

**Comment by kamrutha** [comment]
@nicolas-raoul  Yeah, I will work on it after I complete the current one.

**Comment by venkatesh2000** [comment]
@nicolas-raoul Hi, I'm new to this project and to open source contributions itself. I can reproduce this bug in v2.11.0. However, I can't seem to do the same after checking out the master branch and launching the app in my device. Am I missing something? Forgive me if my question is too naive.

**Comment by nicolas-raoul** [comment]
Maybe the bug has been fixed? Could you please send screenshots?
Thanks! 🙂

**Comment by venkatesh2000** [comment]
@nicolas-raoul Thanks for the reply!! The issue seems to have been fixed as I can't reproduce it in v2.12(Beta release). I've attached the screenshots in my previous comment.

**Comment by mds08011** [comment]
Still occurring in https://github.com/commons-app/apps-android-commons/issues/3359

**Comment by misaochan** [comment]
Just to clarify, I think this is a bit different from #3359 ? In this issue the title of the filename is correct (current upload), but the image shown is from the last image until the upload completes (after which it shows the current image). In #3359 it looks like a complete duplication in Contributions, permanently (unless cache cleared).

**Comment by ashishkumar468** [comment]
Seems to be fixed, not reproducible in the latest releases. We have added placeholders for images while uploading and before loading from the internet. Closing this issue, thanks to everyone for the feedback and help :)
