### ISSUE TITLE
Logout doesn't immediately log users out

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#3547]
**Summary:**
When I logout of the app, I see a "Please wait" loading dialog. After the dialog disappears, I expect to see the log-in page but it doesn't show up. The dialog just disappears and I'm able to use the app as if nothing happened. I'm not able to upload images, though. When I close the app and re-open it I see the login page. 

**Steps to reproduce:** 
1. Open the app
2. Log in to the app
3. Log out using the "Log out" option in the side bar menu

I expect to see the log-in screen after that.

**System logs:**
I'm not sure if they are of any use but here are the logs I could get:

```
V/ActivityThread(26553): updateVisibility : ActivityRecord{1bb6898c token=android.os.BinderProxy@3bbe2786 {fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity}} show : false
D/ActivityManager(  754):  Launching fr.free.nrw.commons, updated priority
D/LocationManagerService(  754): request 3fea43f4 network Request[POWER_LOW network requested=+12s0ms fastest=+12s0ms] from fr.free.nrw.commons(10578)
D/LocationManagerService(  754): request 3fea43f4 gps Request[ACCURACY_FINE gps requested=+12s0ms fastest=+12s0ms] from fr.free.nrw.commons(10578)
E/ContributionsFragment(26553): onFragmentResumed fr.free.nrw.commons.contributions.ContributionsListFragment
E/BufferQueueCore(  188): [fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity] setDefaultMaxBufferCount: setting count to 3, previous is 2
D/StatusBarManagerService(  754): manageDisableList userId=0 what=0x0 pkg=Window{f81301a u0 d0 fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity}
V/WindowStateAnimator(  754): Finishing drawing window Window{f81301a u0 d0 fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity}: mDrawState=DRAW_PENDING
I/Timeline(  754): Timeline: Activity_windows_visible id: ActivityRecord{853b999 u0 fr.free.nrw.commons/.contributions.MainActivity t39860} time:129081857
V/WindowManager(  754): not Base app: Adding window Window{3fccd2bf u0 d0 fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity} at 10 of 14
D/StatusBarManagerService(  754): manageDisableList userId=0 what=0x0 pkg=Window{3fccd2bf u0 d0 fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity}
E/BufferQueueCore(  188): [fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity] setDefaultMaxBufferCount: setting count to 3, previous is 2
V/WindowStateAnimator(  754): Finishing drawing window Window{3fccd2bf u0 d0 fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity}: mDrawState=DRAW_PENDING
V/WindowStateAnimator(  754): Finishing drawing window Window{3fccd2bf u0 d0 fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity}: mDrawState=HAS_DRAWN
V/WindowManager(  754): not Base app: Adding window Window{3205dbdb u0 d0 fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity} at 11 of 15
W/System.err(26553): remove failed: ENOENT (No such file or directory) : /data/data/fr.free.nrw.commons/cache/okhttp-cache/99ec56b47be5d8d13a33c691c3ef9da3.0
W/System.err(26553): remove failed: ENOENT (No such file or directory) : /data/data/fr.free.nrw.commons/cache/okhttp-cache/99ec56b47be5d8d13a33c691c3ef9da3.1
E/BufferQueueCore(  188): [fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity] setDefaultMaxBufferCount: setting count to 3, previous is 2
V/WindowStateAnimator(  754): Finishing drawing window Window{3205dbdb u0 d0 fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity}: mDrawState=DRAW_PENDING
V/WindowStateAnimator(  754): Finishing drawing window Window{3205dbdb u0 d0 fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity}: mDrawState=HAS_DRAWN
W/System.err(26553): remove failed: ENOENT (No such file or directory) : /data/data/fr.free.nrw.commons/cache/okhttp-cache/99ec56b47be5d8d13a33c691c3ef9da3.0
W/System.err(26553): remove failed: ENOENT (No such file or directory) : /data/data/fr.free.nrw.commons/cache/okhttp-cache/99ec56b47be5d8d13a33c691c3ef9da3.1
D/StatusBarManagerService(  754): manageDisableList userId=0 what=0x0 pkg=Window{f81301a u0 d0 fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity}
I/ActivityManager(  754): Start proc 31146:fr.free.nrw.commons:auth/u0a578 for service fr.free.nrw.commons/.auth.WikiAccountAuthenticatorService
W/ResourcesManager(31146): getTopLevelResources: /data/app/fr.free.nrw.commons-1/base.apk / 1.0 running in fr.free.nrw.commons rsrc of package null
I/ACRA    (31146): ACRA is enabled for fr.free.nrw.commons, initializing...
W/System.err(31146): remove failed: ENOENT (No such file or directory) : /data/data/fr.free.nrw.commons/shared_prefs/fr.free.nrw.commons_preferences.xml.bak
W/System.err(31146): remove failed: ENOENT (No such file or directory) : /data/data/fr.free.nrw.commons/shared_prefs/MapboxSharedPreferences.xml.bak
D/SoLoader(31146): adding application source: com.facebook.soloader.DirectorySoSource[root = /data/app/fr.free.nrw.commons-1/lib/arm flags = 0]
D/SoLoader(31146): adding backup source from : com.facebook.soloader.ApkSoSource[root = /data/data/fr.free.nrw.commons/lib-main flags = 1]
D/SoLoader(31146): Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /data/app/fr.free.nrw.commons-1/lib/arm flags = 0]
D/SoLoader(31146): Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/fr.free.nrw.commons/lib-main flags = 1]
V/fb-UnpackingSoSource(31146): locked dso store /data/data/fr.free.nrw.commons/lib-main
V/fb-UnpackingSoSource(31146): releasing dso store lock for /data/data/fr.free.nrw.commons/lib-main (from syncer thread)
V/fb-UnpackingSoSource(31146): not releasing dso store lock for /data/data/fr.free.nrw.commons/lib-main (syncer thread started)
D/SoLoader(31146): libmapbox-gl.so not found on /data/data/fr.free.nrw.commons/lib-main
D/SoLoader(31146): libmapbox-gl.so found on /data/app/fr.free.nrw.commons-1/lib/arm
V/AlarmManagerEXT(  754): <AccPackages> fr.free.nrw.commons
E/SQLiteLog(26553): (28) file unlinked while open: /data/data/fr.free.nrw.commons/databases/commons.db
W/System.err(26553): remove failed: ENOENT (No such file or directory) : /data/data/fr.free.nrw.commons/cache/image_cache/v2.ols100.1
```

**Device and Android version:** 
Samsung SM-J111F, Android 5.1.1
 
**Commons app version:** 
2.12.3.623

**Comment by avivith** [comment]
Hi. I would like to work on this issue.

**Comment by macgills** [comment]
You are assigned @avivith

**Comment by madhurgupta10** [comment]
Just to mention that this issue is similar to #2764

**Comment by macgills** [comment]
My apologies @madhurgupta10, that ticket is a year old and doesn't go into as much detail so I am considering closing it and instead focusing on this ticket.

Would you like to be assigned to this ticket and do you have the capacity for it currently?

**Comment by madhurgupta10** [comment]
> My apologies @madhurgupta10, that ticket is a year old and doesn't go into as much detail so I am considering closing it and instead focusing on this ticket.
> 
> Would you like to be assigned to this ticket and do you have the capacity for it currently?

The old ticket can be closed and I am working on other issues right now. I would be happy if @avivith picks it up!

**Comment by sivaraam** [comment]
> Just to mention that this issue is similar to #2764

I'm not sure if this is a duplicate of that for the following reason: In my case, I actually don't see the login page at all after I logout. I waited for around 2 minutes and still didn't see the logout screen. 🤷‍♂ As mentioned in the description, I'm even able to go to other places such as Nearby, Explore etc.

**Comment by madhurgupta10** [comment]
> > Just to mention that this issue is similar to #2764
> 
> I'm not sure if this is a duplicate of that for the following reason: In my case, I actually don't see the login page at all after I logout. I waited for around 2 minutes and still didn't see the logout screen. 🤷‍♂ As mentioned in the description, I'm even able to go to other places such as Nearby, Explore etc.

One of the processes in logout is causing the delay, I remember trying to find out the root cause of it but stopped working on it after a few days. This is issue is subjective to the user, for me I can log out instantly but sometimes I face the same issue.

**Comment by macgills** [comment]
With this ticket I think we can "make logout work good"

I am not entirely aware how login/out works but can't we just delete a local token or something?

**Comment by avivith** [comment]
Sadly, I'm a little sick and don't manage to work currently. I hope someone else could solve this issue.

**Comment by sivaraam** [comment]
@avivith It's fine. Take care of yourself.

**Comment by gouri-panda** [comment]
Can I work on this issue? :)

**Comment by madhurgupta10** [comment]
@gouri-panda Sure but before implementation please discuss your approach and the root cause of the delay.

**Comment by sivaraam** [comment]
@gouri-panda Were you able to find the cause of this issue? Are you still working on this?

**Comment by gouri-panda** [comment]
@sivaraam  I am still working on this issue. Unfortunately, I can't find the root cause of this issue. If anyone interested in this issue. Please feel free to take this issue.:)

**Comment by sivaraam** [comment]
@gouri-panda Thanks for the update. I'm unassigning the issue for now. Let us know if you get any leads, I'll assign it back :)

**Comment by madhurgupta10** [comment]
@sivaraam @macgills What I found out that particularly ``` updateAllDatabases(); ``` in 
```
sessionManager.logout()
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(() -> {
                    Timber.d("All accounts have been removed");
                    clearImageCache();
                    //TODO: fix preference manager
                    defaultPrefs.clearAll();
                    defaultPrefs.putBoolean("firstrun", false);
                    updateAllDatabases();
                    logoutListener.onLogoutComplete();
                });
```
is responsible for the delay!

**Comment by gouri-panda** [comment]
@madhurgupta10  If we don't execute the above code still it doesn't go back to the LoginActivity.

> Cannot access database on the main thread since it may potentially lock the UI for a long period of time.
 It works on the background thread. Does this affect the UI? correct me if I am wrong:)

**Comment by 318anushka** [comment]
> @sivaraam @macgills What I found out that particularly `updateAllDatabases();` in
> 

Yes, particularly deleting table `contributionDao.deleteAll();` is what causing it. Method which creates login activity is never called.

**Comment by madhurgupta10** [comment]
> If we don't execute the above code still it doesn't go back to the LoginActivity.

@gouri-panda It does redirect to LoginActivity for me if I comment out that particular line.

> It works on the background thread. Does this affect the UI? correct me if I am wrong:)

Ideally, it should but I got this exception while debugging.

**Comment by macgills** [comment]
```
 .observeOn(AndroidSchedulers.mainThread())
```
In English "everything below this line runs on the main thread"

**Comment by sivaraam** [comment]
I'm re-opening this as I still observe the issue I describe in the description when using the `prodDebug` version built with master pointing at 743e24cd71341058b74c38ea08a3018450c3c404 which has this PR merged.

**Comment by macgills** [comment]
@sivaraam it logs out for me

**Comment by macgills** [comment]
I guess what could be happening is that the logout call failed somehow, we now have actual error printing for this so that should be obvious in logcat. We do however probably want to alert the user that logout failed, should that situation arise

**Comment by sivaraam** [comment]
This is the "Error" only log that I see after I hit the "Yes" for the logout dialog:

```
04-17 00:46:23.221 23246-23246/? E/Zygote: MountEmulatedStorage()
04-17 00:46:23.221 23246-23246/? E/Zygote: v2
04-17 00:46:23.231 23246-23246/? E/SELinux: [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
04-17 00:46:25.974 190-190/? E/BufferQueueCore: [fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity] setDefaultMaxBufferCount: setting count to 3, previous is 2 
04-17 00:46:26.034 17482-17482/fr.free.nrw.commons E/ViewRootImpl: sendUserActionEvent() mView == null
04-17 00:46:27.125 17482-17482/fr.free.nrw.commons E/ViewRootImpl: sendUserActionEvent() mView == null
04-17 00:46:27.155 23265-23265/? E/Zygote: MountEmulatedStorage()
04-17 00:46:27.155 23265-23265/? E/Zygote: v2
04-17 00:46:27.155 23265-23265/? E/SELinux: [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
04-17 00:46:27.165 23265-23265/? E/art: setrlimit(RLIMIT_CORE) failed for pid 23265: Operation not permitted
04-17 00:46:27.405 23283-23283/? E/SELinux: [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
04-17 00:46:27.465 23284-23284/? E/Zygote: MountEmulatedStorage()
04-17 00:46:27.465 23284-23284/? E/Zygote: v2
04-17 00:46:27.475 23284-23284/? E/SELinux: [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
04-17 00:46:29.017 17482-23180/fr.free.nrw.commons E/SQLiteLog: (28) file unlinked while open: /data/data/fr.free.nrw.commons/databases/commons.db
04-17 00:46:29.057 23327-23327/? E/Zygote: MountEmulatedStorage()
04-17 00:46:29.057 23327-23327/? E/Zygote: v2
04-17 00:46:29.087 23327-23327/? E/SELinux: [DEBUG] get_category: variable seinfo: untrusted sensitivity: NULL, cateogry: NULL
04-17 00:46:29.197 755-834/? E/ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ id=134, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]
04-17 00:46:29.247 17482-23180/fr.free.nrw.commons E/SQLiteLog: (1032) statement aborts at 13: [Delete FROM contribution] 
04-17 00:46:29.267 17482-17482/fr.free.nrw.commons E/-$$Lambda$mvgeVM6S-0Wc8: android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
    #################################################################
    Error Code : 1032 (SQLITE_READONLY_DBMOVED)
    Caused By : Database or Journal file have been removed.
    	(attempt to write a readonly database (code 1032))
    #################################################################
        at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:878)
        at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
        at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
        at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeUpdateDelete(FrameworkSQLiteStatement.java:46)
        at fr.free.nrw.commons.contributions.ContributionDao_Impl.deleteAll(ContributionDao_Impl.java:635)
        at fr.free.nrw.commons.CommonsApplication.updateAllDatabases(CommonsApplication.java:302)
        at fr.free.nrw.commons.CommonsApplication.lambda$clearApplicationData$102$CommonsApplication(CommonsApplication.java:277)
        at fr.free.nrw.commons.-$$Lambda$CommonsApplication$He8l_y9qlRAiuRQkwTokla5VRAk.run(lambda)
        at io.reactivex.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:35)
        at io.reactivex.Completable.subscribe(Completable.java:2309)
        at io.reactivex.internal.operators.completable.CompletableAndThenCompletable$SourceObserver.onComplete(CompletableAndThenCompletable.java:67)
        at io.reactivex.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onComplete(CompletablePeek.java:115)
        at io.reactivex.internal.operators.completable.CompletableFromObservable$CompletableFromObservableObserver.onComplete(CompletableFromObservable.java:56)
        at io.reactivex.internal.observers.BasicFuseableObserver.onComplete(BasicFuseableObserver.java:119)
        at io.reactivex.internal.operators.observable.ObservableScalarXMap$ScalarDisposable.run(ObservableScalarXMap.java:251)
        at io.reactivex.internal.operators.observable.ObservableJust.subscribeActual(ObservableJust.java:35)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.completable.CompletableFromObservable.subscribeActual(CompletableFromObservable.java:29)
        at io.reactivex.Completable.subscribe(Completable.java:2309)
        at io.reactivex.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
        at io.reactivex.Completable.subscribe(Completable.java:2309)
        at io.reactivex.internal.operators.completable.CompletableAndThenCompletable.subscribeActual(CompletableAndThenCompletable.java:35)
        at io.reactivex.Completable.subscribe(Completable.java:2309)
        at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
04-17 00:46:29.307 23344-23344/? E/Zygote: MountEmulatedStorage()
04-17 00:46:29.307 23344-23344/? E/Zygote: v2
04-17 00:46:29.317 23344-23344/? E/SELinux: [DEBUG] get_category: variable seinfo: platform sensitivity: NULL, cateogry: NULL
04-17 00:46:29.407 23362-23362/? E/Zygote: MountEmulatedStorage()
04-17 00:46:29.407 23362-23362/? E/Zygote: v2
04-17 00:46:29.417 23362-23362/? E/SELinux: [DEBUG] get_category: variable seinfo: release sensitivity: NULL, cateogry: NULL
04-17 00:46:29.627 23377-23377/? E/Zygote: MountEmulatedStorage()
04-17 00:46:29.627 23377-23377/? E/Zygote: v2
04-17 00:46:29.637 23377-23377/? E/SELinux: [DEBUG] get_category: variable seinfo: untrusted sensitivity: NULL, cateogry: NULL
04-17 00:46:29.817 23415-23415/? E/Zygote: MountEmulatedStorage()
04-17 00:46:29.817 23415-23415/? E/Zygote: v2
04-17 00:46:29.828 23415-23415/? E/SELinux: [DEBUG] get_category: variable seinfo: untrusted sensitivity: NULL, cateogry: NULL
04-17 00:46:29.898 23284-23284/? E/SQLiteLog: (283) recovered 10 frames from WAL file /data/data/com.whatsapp/databases/msgstore.db-wal
04-17 00:46:30.038 23436-23436/? E/Zygote: MountEmulatedStorage()
04-17 00:46:30.038 23436-23436/? E/Zygote: v2
04-17 00:46:30.038 23436-23436/? E/SELinux: [DEBUG] get_category: variable seinfo: untrusted sensitivity: NULL, cateogry: NULL
04-17 00:46:30.078 23284-23284/? E/SQLiteLog: (284) automatic index on sqlite_sq_A04B2D00(key_remote_jid)
04-17 00:46:30.078 23284-23284/? E/SQLiteLog: (284) automatic index on sqlite_sq_A04B2A80(chat_row_id)
04-17 00:46:30.538 23475-23475/? E/Zygote: MountEmulatedStorage()
04-17 00:46:30.538 23475-23475/? E/Zygote: v2
04-17 00:46:30.548 23475-23475/? E/SELinux: [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
04-17 00:46:30.668 23497-23497/? E/Zygote: MountEmulatedStorage()
04-17 00:46:30.668 23497-23497/? E/Zygote: v2
04-17 00:46:30.678 23497-23497/? E/SELinux: [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
04-17 00:46:30.909 23284-23456/? E/SQLiteLog: (283) recovered 82 frames from WAL file /data/data/com.whatsapp/databases/axolotl.db-wal
04-17 00:46:31.719 23284-23456/? E/SQLiteLog: (283) recovered 15 frames from WAL file /data/data/com.whatsapp/databases/location.db-wal
04-17 00:46:31.799 23533-23533/? E/Zygote: MountEmulatedStorage()
04-17 00:46:31.799 23533-23533/? E/Zygote: v2
04-17 00:46:31.809 23533-23533/? E/SELinux: [DEBUG] get_category: variable seinfo: platform sensitivity: NULL, cateogry: NULL
04-17 00:46:32.250 23557-23557/? E/Zygote: MountEmulatedStorage()
04-17 00:46:32.250 23557-23557/? E/Zygote: v2
04-17 00:46:32.260 23557-23557/? E/SELinux: [DEBUG] get_category: variable seinfo: untrusted sensitivity: NULL, cateogry: NULL
04-17 00:46:32.320 23284-23427/? E/SQLiteLog: (283) recovered 3 frames from WAL file /data/data/com.whatsapp/databases/wa.db-wal
04-17 00:46:32.370 23533-23555/? E/ActivityThread: Failed to find provider info for com.samsung.android.email.preference.provider
04-17 00:46:32.530 23533-23533/? E/ActivityThread: Failed to find provider info for com.samsung.android.email.provider
04-17 00:46:32.600 23533-23533/? E/ActivityThread: Failed to find provider info for com.samsung.android.email.preference.provider
04-17 00:46:32.680 23581-23581/? E/Zygote: MountEmulatedStorage()
04-17 00:46:32.680 23581-23581/? E/Zygote: v2
04-17 00:46:32.700 23581-23581/? E/SELinux: [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
04-17 00:46:33.531 23533-23578/? E/ActivityThread: Failed to find provider info for com.samsung.android.email.provider
04-17 00:46:34.612 23623-23623/? E/Zygote: MountEmulatedStorage()
04-17 00:46:34.612 23623-23623/? E/Zygote: v2
04-17 00:46:34.622 23623-23623/? E/SELinux: [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
04-17 00:46:35.863 23284-23528/? E/SQLiteLog: (283) recovered 79 frames from WAL file /data/data/com.whatsapp/databases/media.db-wal
04-17 00:46:36.604 23665-23665/? E/Zygote: MountEmulatedStorage()
04-17 00:46:36.604 23665-23665/? E/Zygote: v2
04-17 00:46:36.604 23665-23665/? E/SELinux: [DEBUG] get_category: variable seinfo: platform sensitivity: NULL, cateogry: NULL
04-17 00:46:36.944 23687-23687/? E/Zygote: MountEmulatedStorage()
04-17 00:46:36.944 23687-23687/? E/Zygote: v2
04-17 00:46:36.944 23687-23687/? E/SELinux: [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
04-17 00:46:37.135 1310-1840/? E/art: invalid stream - problem with parameter iterator in /data/app/com.google.android.gms-2/base.apk:classes3.dex for method void com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.setSoWriteTimeout(int)
04-17 00:46:37.205 23705-23705/? E/Zygote: MountEmulatedStorage()
04-17 00:46:37.205 23705-23705/? E/Zygote: v2
04-17 00:46:37.205 23705-23705/? E/SELinux: [DEBUG] get_category: variable seinfo: platform sensitivity: NULL, cateogry: NULL
04-17 00:46:37.325 1310-1840/? E/art: invalid stream - problem with parameter iterator in /data/app/com.google.android.gms-2/base.apk:classes3.dex for method void com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.setSoWriteTimeout(int)
04-17 00:46:37.395 23720-23720/? E/Zygote: MountEmulatedStorage()
04-17 00:46:37.395 23720-23720/? E/Zygote: v2
04-17 00:46:37.395 23720-23720/? E/SELinux: [DEBUG] get_category: variable seinfo: release sensitivity: NULL, cateogry: NULL
04-17 00:46:37.625 23735-23735/? E/Zygote: MountEmulatedStorage()
04-17 00:46:37.625 23735-23735/? E/Zygote: v2
04-17 00:46:37.625 23735-23735/? E/SELinux: [DEBUG] get_category: variable seinfo: untrusted sensitivity: NULL, cateogry: NULL
04-17 00:46:37.815 23720-23753/? E/SQLiteLog: (284) automatic index on view_events(_id)
04-17 00:46:39.927 1310-1841/? E/art: invalid stream - problem with parameter iterator in /data/app/com.google.android.gms-2/base.apk:classes3.dex for method void com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.setSoWriteTimeout(int)
04-17 00:46:40.088 1310-1841/? E/art: invalid stream - problem with parameter iterator in /data/app/com.google.android.gms-2/base.apk:classes3.dex for method void com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.setSoWriteTimeout(int)
04-17 00:46:40.838 1310-23772/? E/art: invalid stream - problem with parameter iterator in /data/app/com.google.android.gms-2/base.apk:classes3.dex for method void com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.setSoWriteTimeout(int)
04-17 00:46:41.018 1310-23772/? E/art: invalid stream - problem with parameter iterator in /data/app/com.google.android.gms-2/base.apk:classes3.dex for method void com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.setSoWriteTimeout(int)
04-17 00:46:41.659 22388-23778/? E/art: invalid stream - problem with parameter iterator in /data/app/com.google.android.gms-2/base.apk:classes3.dex for method void com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.setSoWriteTimeout(int)
04-17 00:46:41.799 22388-23778/? E/art: invalid stream - problem with parameter iterator in /data/app/com.google.android.gms-2/base.apk:classes3.dex for method void com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.setSoWriteTimeout(int)
04-17 00:46:41.879 23781-23781/? E/Zygote: MountEmulatedStorage()
04-17 00:46:41.879 23781-23781/? E/Zygote: v2
04-17 00:46:41.889 23781-23781/? E/SELinux: [DEBUG] get_category: variable seinfo: release sensitivity: NULL, cateogry: NULL
04-17 00:46:43.040 23800-23800/? E/Zygote: MountEmulatedStorage()
04-17 00:46:43.040 23800-23800/? E/Zygote: v2
04-17 00:46:43.050 23800-23800/? E/SELinux: [DEBUG] get_category: variable seinfo: untrusted sensitivity: NULL, cateogry: NULL
04-17 00:46:43.821 23827-23827/? E/Zygote: MountEmulatedStorage()
04-17 00:46:43.821 23827-23827/? E/Zygote: v2
04-17 00:46:43.821 23827-23827/? E/SELinux: [DEBUG] get_category: variable seinfo: untrusted sensitivity: NULL, cateogry: NULL
04-17 00:46:46.774 755-1036/? E/Watchdog: !@Sync 3099 [04-17 00:46:46.783]
04-17 00:46:46.884 22388-23860/? E/art: invalid stream - problem with parameter iterator in /data/app/com.google.android.gms-2/base.apk:classes3.dex for method void com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.setSoWriteTimeout(int)
04-17 00:46:47.064 22388-23860/? E/art: invalid stream - problem with parameter iterator in /data/app/com.google.android.gms-2/base.apk:classes3.dex for method void com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.setSoWriteTimeout(int)
04-17 00:46:48.155 23866-23866/? E/Zygote: MountEmulatedStorage()
04-17 00:46:48.155 23866-23866/? E/Zygote: v2
04-17 00:46:48.165 23866-23866/? E/SELinux: [DEBUG] get_category: variable seinfo: untrusted sensitivity: NULL, cateogry: NULL
04-17 00:46:55.623 23903-23903/? E/Zygote: MountEmulatedStorage()
04-17 00:46:55.623 23903-23903/? E/Zygote: v2
04-17 00:46:55.633 23903-23903/? E/SELinux: [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
04-17 00:47:00.167 755-780/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!
04-17 00:47:01.188 23925-23925/? E/Zygote: MountEmulatedStorage()
04-17 00:47:01.188 23925-23925/? E/Zygote: v2
04-17 00:47:01.188 23925-23925/? E/SELinux: [DEBUG] get_category: variable seinfo: untrusted sensitivity: NULL, cateogry: NULL
04-17 00:47:01.358 23941-23941/? E/Zygote: MountEmulatedStorage()
04-17 00:47:01.358 23941-23941/? E/Zygote: v2
04-17 00:47:01.358 23941-23941/? E/SELinux: [DEBUG] get_category: variable seinfo: release sensitivity: NULL, cateogry: NULL
04-17 00:47:02.730 23966-23966/? E/Zygote: MountEmulatedStorage()
04-17 00:47:02.730 23966-23966/? E/Zygote: v2
04-17 00:47:02.740 23966-23966/? E/SELinux: [DEBUG] get_category: variable seinfo: platform sensitivity: NULL, cateogry: NULL
04-17 00:47:02.910 23988-23988/? E/Zygote: MountEmulatedStorage()
04-17 00:47:02.910 23988-23988/? E/Zygote: v2
04-17 00:47:02.920 23988-23988/? E/SELinux: [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
04-17 00:47:03.100 755-3150/? A/ActivityManager: Service done with onDestroy, but executeNesting=2: ServiceRecord{22c6b722 u0 com.google.android.syncadapters.calendar/.CalendarSyncAdapterService}
    android.util.Log$TerribleFailure: Service done with onDestroy, but executeNesting=2: ServiceRecord{22c6b722 u0 com.google.android.syncadapters.calendar/.CalendarSyncAdapterService}
        at android.util.Log.wtf(Log.java:460)
        at android.util.Slog.wtfStack(Slog.java:186)
        at com.android.server.am.ActiveServices.serviceDoneExecutingLocked(ActiveServices.java:2166)
        at com.android.server.am.ActivityManagerService.serviceDoneExecuting(ActivityManagerService.java:21501)
        at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:1052)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3724)
        at android.os.Binder.execTransact(Binder.java:446)
04-17 00:47:05.052 24012-24012/? E/Zygote: MountEmulatedStorage()
04-17 00:47:05.052 24012-24012/? E/Zygote: v2
04-17 00:47:05.062 24012-24012/? E/SELinux: [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
04-17 00:47:05.672 24036-24036/? E/Zygote: MountEmulatedStorage()
04-17 00:47:05.672 24036-24036/? E/Zygote: v2
04-17 00:47:05.682 24036-24036/? E/SELinux: [DEBUG] get_category: variable seinfo: platform sensitivity: NULL, cateogry: NULL
04-17 00:47:16.773 755-1036/? E/Watchdog: !@Sync 3100 [04-17 00:47:16.784]
```

The following is the verbose log:
[commons_app_log.txt](https://github.com/commons-app/apps-android-commons/files/4489333/commons_app_log.txt)

**Comment by sivaraam** [comment]
Let me know if you need more information.

**Comment by macgills** [comment]
Perhaps file a bug report, I would be suspicious of the device/api level.

Potentially we could make `deleteAll` return a completable too but Room should be threadsafe as long as we don't do any manual transactions

**Comment by sivaraam** [comment]
> Perhaps file a bug report, I would be suspicious of the device/api level.
> 

This issue is your bug report. The description should contain the information you need. If you need anything else, let me know.

**Comment by macgills** [comment]
Tried on a 5.1 emulator, worked fine for me, potentially a samsung issue, can't diagnose it any further at this time.

Whoever takes this up maybe try a Room Upgrade, maybe after skimming their release logs/issues?

**Comment by misaochan** [comment]
Thanks for pointing me to this issue, should be fixed by #3649  .

**Comment by sivaraam** [comment]
Sadly as noted in my [earlier comment](https://github.com/commons-app/apps-android-commons/issues/3547#issuecomment-614212820), that PR didn't fix the issue for me. I still observe the behaviour stated in the issue description :( I tried using 2.13.1.793~66f6e2e

**Comment by misaochan** [comment]
Ah sorry, I didn't notice that. I am unable to reproduce this bug on a 5.1 emulator, wonder what could be causing it. Perhaps we should try to upgrade Room as macgills suggests.
