### ISSUE TITLE
"No such column" SQLite error

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3792]
I received a report from one of the WLM guys that our Nearby map does not work for them. They get this error when they try to load it:

![Screenshot_20200602-080638](https://user-images.githubusercontent.com/3611199/83542698-a8657c00-a53e-11ea-99fc-b9dac28fc731.png)

**Device and Android version:** 

Android 10, Pixel 4

**Commons app version:** 

v 2.13 from Play Store beta testing

**Would you like to work on the issue?**

No

**Comment by ashishkumar468** [comment]
Fixed in #3793

**Comment by misaochan** [comment]
Unfortunately this still happens. Logs are in commons-app-private mailing list.

**Comment by misaochan** [comment]
@madhurgupta10 This PR can go to straight to master, no need for 3.0-release
