### ISSUE TITLE
App Crash on Login

### ISSUE THREAD

**Issue by fnordson** [commons-app/apps-android-commons#3914]
**Summary:** 

Login leads to crash of app

**Steps to reproduce:** 

Start App 
Type in login data.
Hit "login" button. 

**System logs:**

```

STACK_TRACE=java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.accounts.Account.hashCode()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2678)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2743)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1490)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6165)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.accounts.Account.hashCode()' on a null object reference
	at android.os.Parcel.readException(Parcel.java:1690)
	at android.os.Parcel.readException(Parcel.java:1637)
	at android.content.IContentService$Stub$Proxy.setSyncAutomaticallyAsUser(IContentService.java:1060)
	at android.content.ContentResolver.setSyncAutomaticallyAsUser(ContentResolver.java:2107)
	at android.content.ContentResolver.setSyncAutomatically(ContentResolver.java:2097)
	at fr.free.nrw.commons.contributions.MainActivity.initMain(MainActivity.java:110)
	at fr.free.nrw.commons.contributions.MainActivity.onCreate(MainActivity.java:84)
	at android.app.Activity.performCreate(Activity.java:6687)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2631)
	... 9 more



```

**Device and Android version:** 

ANDROID_VERSION=7.1.1
PHONE_MODEL=Moto G Play
 
**Commons app version:** 

APP_VERSION_CODE=561
APP_VERSION_NAME=2.12.3

**Would you like to work on the issue?**

I don't have the qualification to work on this issue

**Comment by misaochan** [comment]
Hi, this bug should have been fixed in v2.13.1. Could you register for beta testing and let us know if it fixes the problem for you? Otherwise, the new version should be available to everyone by the end of the week (if everything goes well).

**Comment by fnordson** [comment]
Sure.  
How do I register for beta?

**Comment by fnordson** [comment]
I installed the Beta but the problem still occurs. 
From the crash log I've send:

APP_VERSION_CODE=775
APP_VERSION_NAME=2.13.1
ANDROID_VERSION=7.1.1
PHONE_MODEL=Moto G Play
STACK_TRACE=java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.accounts.Account.name' on a null object reference
	at fr.free.nrw.commons.contributions.ContributionsFragment.setUploadCount(ContributionsFragment.java:363)
	at fr.free.nrw.commons.contributions.ContributionsFragment.onCreateView(ContributionsFragment.java:166)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
	at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1696)
	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:299)
	at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:235)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
	at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
	at android.view.View.measure(View.java:19883)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:19883)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
	at android.view.View.measure(View.java:19883)
	at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1119)
	at android.view.View.measure(View.java:19883)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
	at android.view.View.measure(View.java:19883)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
	at android.view.View.measure(View.java:19883)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:19883)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
	at android.view.View.measure(View.java:19883)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:689)
	at android.view.View.measure(View.java:19883)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2293)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1384)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1637)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1272)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6408)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
	at android.view.Choreographer.doFrame(Choreographer.java:621)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6165)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)

REPORT_ID=798a844b-fdd8-4ccf-953f-3b181b009244

**Comment by fnordson** [comment]
@misaochan 

I installed the Beta but the problem still occurs.
From the crash log I've send:

APP_VERSION_CODE=775
APP_VERSION_NAME=2.13.1
ANDROID_VERSION=7.1.1
PHONE_MODEL=Moto G Play
STACK_TRACE=java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.accounts.Account.name' on a null object reference
at fr.free.nrw.commons.contributions.ContributionsFragment.setUploadCount(ContributionsFragment.java:363)
at fr.free.nrw.commons.contributions.ContributionsFragment.onCreateView(ContributionsFragment.java:166)
at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1696)
at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:299)
at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:235)
at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
at android.view.View.measure(View.java:19883)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
at android.view.View.measure(View.java:19883)
at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
at android.view.View.measure(View.java:19883)
at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1119)
at android.view.View.measure(View.java:19883)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
at android.view.View.measure(View.java:19883)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
at android.view.View.measure(View.java:19883)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
at android.view.View.measure(View.java:19883)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
at android.view.View.measure(View.java:19883)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
at com.android.internal.policy.DecorView.onMeasure(DecorView.java:689)
at android.view.View.measure(View.java:19883)
at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2293)
at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1384)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1637)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1272)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6408)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
at android.view.Choreographer.doCallbacks(Choreographer.java:686)
at android.view.Choreographer.doFrame(Choreographer.java:621)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6165)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)

REPORT_ID=798a844b-fdd8-4ccf-953f-3b181b009244

**Comment by ashishkumar468** [comment]
This seems to be a different one from the one mentioned in the original issue log, @fnordson So just to confirm, you are able to login in successfully but as soon as you get logged in, the app crashes?

**Comment by fnordson** [comment]
@ashishkumar0207 

Just before the app disappears and the crash report pop-up comes up, I think I can see a small text saying that the login was successful. It's just too fast everything and I'm not sure if the text was there the last time. 

From my standpoint it looks like the same behaviour: 
Start App
Type in login data.
Hit "login" button.
App disappears and crash report pop-up comes up.

**Comment by fnordson** [comment]
@misaochan Why has this been closed?  
Is it supposed to be fixed (it isn't on my phone)?  
Fixed in the next version?

**Comment by misaochan** [comment]
The associated PR has been merged, so the issue is auto-closed. It will be released in the next hotfix, which should be soon.
