### ISSUE TITLE
[Bug]: Edit Category Crashes when Previous Button is Clicked

### ISSUE THREAD

**Issue by shashankiitbhu** [commons-app/apps-android-commons#5505]
### Summary

App Crashes When You click Previous Button in Edit Category Activity In Your Contribution

### Steps to reproduce

1. Open the App
2. Select any one of your contributions
3. Click on the Edit Icon in the Category
4. Click Previous Button

### Expected behaviour

App Should go back to the previous page

### Actual behaviour

App Crashes

### Device name

Xaomi 11 Lite NE

### Android version

Android 13

### Commons app version

4.2.1-debug-main

### Screen-shots

https://github.com/commons-app/apps-android-commons/assets/126143257/c979f4c6-1b3c-4c6b-9ca9-8600ec131a50

### Would you like to work on the issue?

Yes

**Comment by psh** [comment]
The stacktrace associatedf with this crash - 
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void fr.free.nrw.commons.upload.categories.UploadCategoryAdapter.setItems(java.util.List)' on a null object reference
  at fr.free.nrw.commons.upload.categories.UploadCategoriesFragment.onPreviousButtonClicked(UploadCategoriesFragment.java:311)
  at fr.free.nrw.commons.upload.categories.UploadCategoriesFragment_ViewBinding$2.doClick(UploadCategoriesFragment_ViewBinding.java:55)
  at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:18)
  at android.view.View.performClick(View.java:7506)
  at android.view.View.performClickInternal(View.java:7483)
  at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
  at android.view.View$PerformClick.run(View.java:29334)
  at android.os.Handler.handleCallback(Handler.java:942)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loopOnce(Looper.java:201)
  at android.os.Looper.loop(Looper.java:288)
  at android.app.ActivityThread.main(ActivityThread.java:7872)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

from a line of code that says

```
    adapter.setItems(null);
```

The adapter is `null` maybe because was never setup?

**Comment by rohit9625** [comment]
This behavior is the same as editing depiction fragments which is solved now.

**Comment by shashankiitbhu** [comment]
But this particular issue is still not solved, I am looking into this issue

**Comment by shashankiitbhu** [comment]
@psh yes ```init()``` is not getting called due to an incorrectly placed check
